# Site settings
title: Hamlet Wood Scout Campsite
email: warden@hamletwood.org.uk
description: "Hamlet Wood Scout Campsite and Training Centre based in Maidstone, Kent."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hamletwood.org.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
